string input
string output
sensor_msgs/Image image
openpose_ros/SparseTensor feature_map
openpose_ros/SparseTensor affinity_field
openpose_ros/SparseTensor confidence_map
---
openpose_ros/Person[] people
openpose_ros/SparseTensor feature_map
openpose_ros/SparseTensor affinity_field
openpose_ros/SparseTensor confidence_map
